Improve git up command
  * now only with remote branch can be rebased

diff --git a/bin/git-up b/bin/git-up
--- a/bin/git-up
+++ b/bin/git-up
@@ -11,14 +11,17 @@ git fetch
 
 for branch in $BRANCHS
 do
-  git checkout $branch
-  git rebase origin/$branch
-  exit_code=$?
-  if [ $exit_code -eq 0 ]; then
-    echo -e "\e[32m# Rebased branch '$branch'\e[0m"
-  else
-    echo -e "\e[31m# Failed to rebase branch '$branch'\e[0m"
-    exit $exit_code
+  have_remote_branch=$(git branch -r | grep -e origin/${branch}\$)
+  if [ "$have_remote_branch" ]; then
+    git checkout $branch
+    git rebase origin/$branch
+    exit_code=$?
+    if [ $exit_code -eq 0 ]; then
+      echo -e "\e[32m# Rebased branch '$branch'\e[0m"
+    else
+      echo -e "\e[31m# Failed to rebase branch '$branch'\e[0m"
+      exit $exit_code
+    fi
   fi
 done
 
